services:
  # Laravel Backend API Service
  - type: web
    name: garment-pos-backend
    env: docker
    rootDir: backend
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: garment-pos-db
          property: connectionString



databases:
  - name: garment-pos-db
    plan: free
